/*==============================================================*/
--GIAO DIEN GIAM SAT TRUC TUYEN-DICH VU 

--Giám sát thời gian phục vụ của dịch vụ hoặc nhân viên thuộc 1 đơn vị.
--Nơi gọi: o	Chọn Menu  Chọn Giám sát  Chọn giám sát dịch vụ  
--Xét quyền Giám sát
--Thư mục lưu hình cảnh báo trên server: 	../IMG/IMGWARNING/                                  
/*==============================================================*/


/*============================================*/
---MAN HINH GIAM SAT TRUC TUYEN DICH VU                       
/*============================================*/

---1. COMBO DON VI******************************

---LOAD DON VI: 
GO

SELECT OFFICEID,OFFICENAME,ORDERINDEX  FROM dbo.OFFICE
WHERE  ISACTIVE=1
ORDER BY ORDERINDEX

GO
---Thực hiện kết nối server đến đơn vị được chọn


SELECT IPDATABASE,DATABASENAME,USERNAME,PASSWORD  FROM dbo.OFFICE
WHERE  OFFICEID='08CNHCM'     ---GIA TRI OFFICEID DUOC CHON

GO

---Nếu không kết nối được 
---Hiển thị thông báo “Kết nối dữ liệu đơn vị” + “Mã – tên đơn vị” + “ không thành công

---2. COMBO DICH VU***************************

---LOAD DICH VU CUA DON VI

SELECT SERVICEID,SERVICENAME FROM dbo.SERVICEINFO
ORDER BY STARTNO

GO


----HIEN THI THOI GIAN PHUC VU CUA MOI QUAY
----QUERY TUNG QUAY
----TRUONG HOP NAY KHI CHUA CHON DICH VU---SE LOAD HET DU LIEU CUA TAT CA CAC DICH VU
----NEU CHON DICH VU NAO THI THAY BIEN: SERVICEID="SO ID CUA DICH VU"
SELECT      SERVICEID
FROM    	dbo.SERVICEINFO
ORDER BY 	SERVICEID

/*============================================*/
---HIEN THI TREN BANG GIAM SAT DICH VU                     
/*============================================*/

---LAY THEO THU TU, QUAY 1-->QUAY N
---1. HIEN THI COT "DICH VU"

SELECT 		CONCAT(SERVICEID,' ',SERVICENAME) AS 'Dịch vụ'
FROM    	dbo.SERVICEINFO
WHERE		SERVICEID='1'      ---LAN LUOT THAY TUNG QUAY TIM THAY O TREN

GO

SELECT*FROM dbo.CUSTOMERS
SELECT  GETDATE()

---CHECK DU LIEU NGAY '12/10/2018'
---2. HIEN THI COT "SO DANG PHUC VU"
BEGIN
SELECT 		MAX(dbo.CUSTOMERS.CUSTOMERNO) AS 'Số đang phục vụ'
FROM    	dbo.CUSTOMERS 
WHERE		dbo.CUSTOMERS.SERVICEID='1'AND dbo.CUSTOMERS.STATUS = '1' AND CONVERT(CHAR(10), TOCOUNTERTIME, 103) ='12/10/2018'    ----'NGAY HIEN TAI dd/mm/yyyy'
END 

GO
-----------------
---3. HIEN THI "PHUC VU HIEN TAI"
BEGIN
SELECT      DATEDIFF("SECOND",dbo.CUSTOMERS.SERVINGTIME, '2018-10-12 08:59:00')   ----GETDATE() ngay gio hien tai (he thong) '2018-10-12 08:55:00'
FROM		dbo.CUSTOMERS 
WHERE		dbo.CUSTOMERS.CUSTOMERNO ='2004' AND dbo.CUSTOMERS.SERVICEID='2'					 ---LA SO DANG PHUC VU CUA CUSTOMER O DICH VU TREN
			AND CONVERT(CHAR(10), TOCOUNTERTIME, 103) = '12/10/2018'  ----  'NGAY HIEN TAI dd/mm/yyyy'
END
GO

----4. Thời gian chờ max của dịch vụ:
------dbo.CUSTOMERS.STATUS = trạng thái của khách hàng: 0-Chờ pv; 1-Đang pv; 2-Lưu lại; 3- Đã pv; 4-Hủy pv; 5-Hủy bởi hệ thống
------Hien thi thoi gian tinh toan: DATEDIFF("bien",---) bien ="s" hay "Second" tinh bang giay, 'n' hay "m" "Minute" tinh bang phut
------Dang cho hien thi bang giay 
BEGIN
SELECT
		MAX(DATEDIFF("SECOND", dbo.CUSTOMERS.TOCOUNTERTIME, '2018-10-12 08:59:00')) AS MAXWAITTIME   ---//Thoi gian phuc vu max cua dv    GETDATE() =ngay gio he thong
FROM    dbo.CUSTOMERS
WHERE   dbo.CUSTOMERS.STATUS = '0' AND dbo.CUSTOMERS.SERVICEID ='2' AND CONVERT(CHAR(10), TOCOUNTERTIME, 103) ='12/10/2018'

END


BEGIN
---5. HIEN THI THONG TIN CON LAI
SELECT		
			ROUND(AVG(DATEDIFF("SECOND", dbo.CUSTOMERS.SERVINGTIME, dbo.CUSTOMERS.FINISHTIME)), 0) AS AVGSERVETIME,		---// HIEN THI "Thoi gian phuc vu trung binh"  cua dv 
			-----CHO HIEN THI VO COT PHUC VU TRUNG BINH
            ROUND(AVG(DATEDIFF("SECOND", dbo.CUSTOMERS.TOCOUNTERTIME, dbo.CUSTOMERS.SERVINGTIME)), 0) AS AVGWAITTIME	---// HIEN THI "Thoi gian cho trung bình" cua dv
			
FROM    	dbo.CUSTOMERS
WHERE   	dbo.CUSTOMERS.STATUS = '3' AND dbo.CUSTOMERS.SERVICEID ='1' AND CONVERT(CHAR(10), TOCOUNTERTIME, 103) ='12/10/2018'   ---'NGAY HIEN TAI dd/mm/yyyy'
END




---DANH DAU CELL TREN DANH SACH CO DICH VU CO GIA TRI VUOT GIOI HAN
---4. LAY DU LIEU MUC GIOI HAN DICH VU TU BANG dbo.SYSTEMCONFIGSERVICEINFO
SELECT  WAITTIMEMAX ,       ----THOI GIAN CHO PHUC VU TOI DA
		SERVICETIMEMAX,     ----THOI GIAN PHUC VU TOI DA
		DISCOUNTITIMEMAX    ----THOI GIAN NGHI GIUA HAI SO LIEN TIEP TOI DA
FROM 	dbo.SYSTEMCONFIGSERVICEINFO
WHERE   SERVICEID='1'   AND OFFICEID ='08CNHCM'     ---"CHON DICH VU"    ---CHON DICH VU

---- NEU KHONG CHECK BO QUA BUOC SO SANH NAY  

---WAITTIMEMAX"   <"CHO LAU NHAT" ----MAU XANH    MAXWAITTIME 
---SERVICETIMEMAX <"THOI GIAN PHUC VU HIEN TAI " MAU VANG

---5. THONG KE THOI GIAN PHUC VU VUOT GIOI HAN
---THUC HIEN BUOC SO SANH NHU TREN THEO TUNG DICH VU ROI CONG LAI

---6. CANH BAO AM THANH VA HINH ANH 

---LAY DU LIEU, THUC HIEN CANH BAO  NEU CO VUOT GIOI HAN CA HAI TRUONG HOP TREN
SELECT*FROM dbo.SYSTEMCONFIGWARNING
WHERE       OFFICEID='08CNHCM'
GO

---7. KHI CHON COMBO DICH VU, LAM GIONG TREN NHUNG CHI CHO HIEN THI DICH VU DUOC CHON
---8. CHECK VA UNCHECK--TO MAU VO O CO DICH VU VUOT GIO HAN


---INSERT DU LIEU DE TEST 
---DA INSERT
---DICH VU 1
---PHUC VU XONG		
INSERT INTO dbo.CUSTOMERS(CUSTOMERNO, SERVICEID,COUNTERID,StaffID,TOCOUNTERTIME,SERVINGTIME,FINISHTIME, STATUS, ISSUEDFROM)		
VALUES	('1002','1','1','51','2018-10-22 17:40:59.000','2018-10-22 17:44:00.000','2018-10-22 17:50:14.000','3','1'),
		('1003','1','1','51','2018-10-22 17:46:59.000','2018-10-22 17:50:30.000','2018-10-22 17:52:14.000','3','1')
GO
--DANG PHUC VU
INSERT INTO dbo.CUSTOMERS(CUSTOMERNO, SERVICEID,COUNTERID,StaffID,TOCOUNTERTIME,SERVINGTIME, STATUS, ISSUEDFROM)
VALUES('1004','1','1','51','2018-10-22 17:47:59.000','2018-10-22 17:53:30.000','1','1')
GO
---DANG CHO
INSERT INTO dbo.CUSTOMERS(CUSTOMERNO, SERVICEID,TOCOUNTERTIME, STATUS, ISSUEDFROM)	
VALUES		('1005','1','2018-10-22 17:50:59.000','0','1')
GO


---DICH VU 2
---DA PHUC VU		
INSERT INTO dbo.CUSTOMERS(CUSTOMERNO, SERVICEID,COUNTERID,StaffID,TOCOUNTERTIME,SERVINGTIME,FINISHTIME, STATUS, ISSUEDFROM)		
VALUES	('2002','2','3','53','2018-10-22 17:40:59.000','2018-10-22 17:44:00.000','2018-10-22 17:50:14.000','3','1'),
		('2003','2','3','53','2018-10-22 17:46:59.000','2018-10-22 17:50:30.000','2018-10-22 17:52:14.000','3','1')
GO
---DANG PHUC VU
INSERT INTO dbo.CUSTOMERS(CUSTOMERNO, SERVICEID,COUNTERID,StaffID,TOCOUNTERTIME,SERVINGTIME, STATUS, ISSUEDFROM)
VALUES('2004','2','3','53','2018-10-22 17:47:59.000','2018-10-22 17:58:30.000','1','1')
GO	
---DANG CHO
INSERT INTO dbo.CUSTOMERS(CUSTOMERNO, SERVICEID,TOCOUNTERTIME, STATUS, ISSUEDFROM)	
VALUES		('2005','2','2018-10-22 17:50:59.000','0','1')
GO

---DICH VU 3
---PHUC VU XONG
INSERT INTO dbo.CUSTOMERS(CUSTOMERNO, SERVICEID,COUNTERID,StaffID,TOCOUNTERTIME,SERVINGTIME,FINISHTIME, STATUS, ISSUEDFROM)		
VALUES	('3002','3','5','55','2018-10-22 17:40:59.000','2018-10-22 17:44:00.000','2018-10-22 17:50:14.000','3','1'),
		('3003','3','5','55','2018-10-22 17:46:59.000','2018-10-22 17:50:30.000','2018-10-22 17:52:14.000','3','1')
GO
---DANG PHUC VU
INSERT INTO dbo.CUSTOMERS(CUSTOMERNO, SERVICEID,COUNTERID,StaffID,TOCOUNTERTIME,SERVINGTIME,STATUS, ISSUEDFROM)
VALUES('3004','3','5','55','2018-10-22 18:20:59.000','2018-10-22 18:40:30.000','1','1')
GO
---DANG CHO
INSERT INTO dbo.CUSTOMERS(CUSTOMERNO, SERVICEID,TOCOUNTERTIME, STATUS, ISSUEDFROM)	
VALUES		('3005','3','2018-10-22 17:52:59.000','0','1')
GO




---------------------------------------------------------------------------

---XOA DU LIEU TEST
DELETE [dbo].CUSTOMERS WHERE CONVERT(CHAR(10), TOCOUNTERTIME, 103) ='22/10/2018'

---XEM DU LIEU DA ADD
SELECT*FROM [dbo].CUSTOMERS  WHERE CONVERT(CHAR(10), TOCOUNTERTIME, 103) ='22/10/2018'

SELECT*FROM [dbo].SERVICEINFO 

SELECT*FROM [dbo].SERVICEINFO
GO
SELECT*FROM [dbo].COUNTERSERVICE


------test thoi gian

---3. HIEN THI "PHUC VU HIEN TAI"

SELECT GETDATE()
GO
BEGIN
SELECT      dbo.CUSTOMERS.SERVINGTIME,
			DATEDIFF("SECOND",dbo.CUSTOMERS.SERVINGTIME, GETDATE())   ----GETDATE() ngay gio hien tai (he thong) '2018-10-12 08:55:00'
FROM		dbo.CUSTOMERS 
WHERE		dbo.CUSTOMERS.CUSTOMERNO ='1001' AND dbo.CUSTOMERS.SERVICEID='1'					 ---LA SO DANG PHUC VU CUA CUSTOMER O DICH VU TREN
			AND CONVERT(CHAR(10), TOCOUNTERTIME, 103) = '23/10/2018'  ----  'NGAY HIEN TAI dd/mm/yyyy'
END
GO

