SELECT*FROM dbo.CUSTOMERS

BEGIN
DECLARE @TIMEOFF INT
	IF (SELECT COUNT(dbo.CUSTOMERS.STATUS) 
				FROM  dbo.CUSTOMERS
				WHERE dbo.CUSTOMERS.COUNTERID ='3'		--- 'BIEN DV' 
				AND CONVERT(CHAR(10), TOCOUNTERTIME, 103) = '1/11/2018')='0'
				SET @TIMEOFF='0'
	ELSE
		SELECT		@TIMEOFF= DATEDIFF("SECOND", MAX(dbo.CUSTOMERS.FINISHTIME),GETDATE())
		FROM    	dbo.CUSTOMERS
		WHERE   	dbo.CUSTOMERS.STATUS = '3' AND dbo.CUSTOMERS.COUNTERID ='3'		--- 'BIEN DV' 
			AND CONVERT(CHAR(10), TOCOUNTERTIME, 103) = '1/11/2018'
END
SELECT @TIMEOFF AS 'Thoi gian nghi giua hai so thu tu'